name: hadolint

on:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: hadolint
        uses: reviewdog/action-hadolint@86131b6bbba35ebe75ddf6febb787908493315f9 # v1.49.0
        with:
          hadolint_ignore: DL3008
          reporter: github-pr-review
          fail_on_error: true
