name: hadolint

on:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: hadolint
        uses: reviewdog/action-hadolint@b7bf2dbd1645be41a04253c66c91487fe3f48bd1 # v1.48.1
        with:
          hadolint_ignore: DL3008
          reporter: github-pr-review
          fail_on_error: true
