name: hadolint

on:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: hadolint
        uses: reviewdog/action-hadolint@86131b6bbba35ebe75ddf6febb787908493315f9 # v1.49.0
        with:
          hadolint_ignore: DL3008
          reporter: github-pr-review
          fail_on_error: true
